### ISSUE TITLE
No Such Ghost blog, check your url.

### ISSUE THREAD

**Issue by ghost** [Litterfeldt/GhostWriter#6]
I have a self-hosted blog at: http://pakhuis.thijsvanulden.nl:2368 and this URL does not work in the app. Version 1.1.2

**Comment by lowenbjer** [comment]
Unfortunately the ghost api does not support non secure urls (http instead of https). This is because you otherwise would be exposing your username and password in plain text and would be vulnerable to a man in the middle attack.

Put your blog behind SSL is the only thing that will solve this, this is not a bug in GhostWriter but rather a feature of the Ghost blog API
